### ISSUE TITLE
Definition of Pins

### ISSUE THREAD

**Issue by Dancopy** [snakeye/matrix-clock-2#1]
Sorry if I'm wrong friend but, I have not seen and I do not know what is the definition of the pins of the Matrix and the DS3231 to the ESP8266; And here, the ESP connects to WiFi over IP? Because I did not see SSID and no password! Thanks for the code

**Comment by snakeye** [comment]
LED matrix uses MAX7219 chip and therefore requires five wires to connect - Ground, +5V, DIN, CLK, CS. DS3231 is connected by I2C bus and therefore requires two wires - SDA and SCL. The pins are marked on the schematic
![](https://raw.githubusercontent.com/snakeye/matrix-clock-2/master/images/schematics%20v1.png)

WiFi connection is configured by the WiFi manager library, please refer the documentation - https://github.com/tzapu/WiFiManager

**Comment by Dancopy** [comment]
Is that I thought that the pins of MAX7219 and DS3231 should be declared in the sketch but, I saw that only the CS pin is declared here: const int pinDisplayCS = 16. Do the other pins (DIN and CLK) need not be declared? Thank you++

**Comment by snakeye** [comment]
Ah, now I see. 

For MAX7219 the only manual definition is CS pin. Two others are defined in SPI.h, their connections are DIN - GPIO13 (HSPID) and CLK - GPIO14 (HSPICLK).

For DS3231 connection refer to the RTC library documentation - https://github.com/Makuna/Rtc/wiki#connecting-the-devices

**Comment by Dancopy** [comment]
OK! Thank you very much

**Comment by Dancopy** [comment]
Hi Andrey! What paper or film did you use to spread the displays? It was beautiful! Thank you
________________________________
De: Andrey Ovcharov <notifications@github.com>
Enviado: terça-feira, 20 de novembro de 2018 09:36
Para: snakeye/matrix-clock-2
Cc: Dancopy; Author
Assunto: Re: [snakeye/matrix-clock-2] Definition of Pins (#1)


Ah, now I see.

For MAX7219 the only manual definition is CS pin. Two others are defined in SPI.h, their connections are DIN - GPIO13 (HSPID) and CLK - GPIO14 (HSPICLK).

For DS3231 connection refer to the RTC library documentation - https://github.com/Makuna/Rtc/wiki#connecting-the-devices

**Comment by snakeye** [comment]
It's some white semi-transparent film I have for years. I don't remember where it was taken from.
